---
apiVersion: v1
kind: Service
metadata:
  name: orderer0-bankconsortiumbcnet-com
  namespace: bankconsortiumbcnet
  labels:
    run: orderer0-bankconsortiumbcnet-com
spec:
  type: NodePort
  selector:
    name: orderer0-bankconsortiumbcnet
  ports:
  - protocol: TCP
    nodePort: 30000
    targetPort: 30000
    port: 30000
    name: grpc  

---
apiVersion: v1
kind: Service
metadata:
  name: orderer1-bankconsortiumbcnet-com
  namespace: bankconsortiumbcnet
  labels:
    run: orderer1-bankconsortiumbcnet-com
spec:
  type: NodePort
  selector:
    name: orderer1-bankconsortiumbcnet
  ports:
  - protocol: TCP
    nodePort: 30001
    targetPort: 30001
    port: 30001
    name: grpc  

