---
apiVersion: v1
kind: Service
metadata:
  name: ca-sbi-bankconsortiumbcnet-com
  namespace: bankconsortiumbcnet
  labels:
    run: ca-sbi-bankconsortiumbcnet-com
spec:
  type: NodePort
  selector:
    name: ca-sbi-bankconsortiumbcnet
  ports:
  - protocol: TCP
    nodePort: 30101
    targetPort: 30101
    port: 30101
    name: grpc
    
    
---
apiVersion: v1
kind: Service
metadata:
  name: ca-hdfc-bankconsortiumbcnet-com
  namespace: bankconsortiumbcnet
  labels:
    run: ca-hdfc-bankconsortiumbcnet-com
spec:
  type: NodePort
  selector:
    name: ca-hdfc-bankconsortiumbcnet
  ports:
  - protocol: TCP
    nodePort: 30102
    targetPort: 30102
    port: 30102
    name: grpc
    
---
apiVersion: v1
kind: Service
metadata:
  name: ca-icici-bankconsortiumbcnet-com
  namespace: bankconsortiumbcnet
  labels:
    run: ca-icici-bankconsortiumbcnet-com
spec:
  type: NodePort
  selector:
    name: ca-icici-bankconsortiumbcnet
  ports:
  - protocol: TCP
    nodePort: 30103
    targetPort: 30103
    port: 30103
    name: grpc
    
