---
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:

    # SampleOrg defines an MSP using the sampleconfig.  It should never be used
    # in production but may be used as a template for other definitions
    - &OrdererOrg
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: OrdererOrg

        # ID to load the MSP definition as
        ID: OrdererMSP

        # MSPDir is the filesystem path which contains the MSP configuration
        MSPDir: crypto-config/ordererOrganizations/bankconsortiumbcnet-com/msp
        # Policies defines the set of policies at this level of the config tree
        # For organization policies, their canonical path is usually
        #   /Channel/<Application|Orderer>/<OrgName>/<PolicyName>
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"
        
        
    - &sbi
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: sbiMSP

        # ID to load the MSP definition as
        ID: sbiMSP

        MSPDir: crypto-config/peerOrganizations/sbi-bankconsortiumbcnet-com/msp

        # Policies defines the set of policies at this level of the config tree
        # For organization policies, their canonical path is usually
        #   /Channel/<Application|Orderer>/<OrgName>/<PolicyName>
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('sbiMSP.admin', 'sbiMSP.peer', 'sbiMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('sbiMSP.admin', 'sbiMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('sbiMSP.admin')"

        # leave this flag set to true.

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0-sbi-bankconsortiumbcnet-com
              Port: 30011
    - &hdfc
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: hdfcMSP

        # ID to load the MSP definition as
        ID: hdfcMSP

        MSPDir: crypto-config/peerOrganizations/hdfc-bankconsortiumbcnet-com/msp

        # Policies defines the set of policies at this level of the config tree
        # For organization policies, their canonical path is usually
        #   /Channel/<Application|Orderer>/<OrgName>/<PolicyName>
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('hdfcMSP.admin', 'hdfcMSP.peer', 'hdfcMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('hdfcMSP.admin', 'hdfcMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('hdfcMSP.admin')"

        # leave this flag set to true.

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0-hdfc-bankconsortiumbcnet-com
              Port: 30013
    - &icici
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: iciciMSP

        # ID to load the MSP definition as
        ID: iciciMSP

        MSPDir: crypto-config/peerOrganizations/icici-bankconsortiumbcnet-com/msp

        # Policies defines the set of policies at this level of the config tree
        # For organization policies, their canonical path is usually
        #   /Channel/<Application|Orderer>/<OrgName>/<PolicyName>
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('iciciMSP.admin', 'iciciMSP.peer', 'iciciMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('iciciMSP.admin', 'iciciMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('iciciMSP.admin')"

        # leave this flag set to true.

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0-icici-bankconsortiumbcnet-com
              Port: 30017

    - &pnb
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: pnbMSP
        # ID to load the MSP definition as
        ID: pnbMSP
        MSPDir: crypto-config/peerOrganizations/pnb-bankconsortiumbcnet-com/msp
        AdminPrincipal: Role.MEMBER
        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0-pnb-bankconsortiumbcnet-com
              Port: 30023
#newanchorpeer
################################################################################
#
#   SECTION: Orderer
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for orderer related parameters
#
################################################################################
Orderer: &OrdererDefaults

    # Orderer Type: The orderer implementation to start
    # Available types are "solo" and "kafka"
    OrdererType: kafka

    Addresses:

        - orderer0-bankconsortiumbcnet-com:30000 
        - orderer1-bankconsortiumbcnet-com:30001 
    # Batch Timeout: The amount of time to wait before creating a batch
    BatchTimeout: 2s

    # Batch Size: Controls the number of messages batched into a block
    BatchSize:

        # Max Message Count: The maximum number of messages to permit in a batch
        MaxMessageCount: 10

        # Absolute Max Bytes: The absolute maximum number of bytes allowed for
        # the serialized messages in a batch.
        AbsoluteMaxBytes: 99 MB

        # Preferred Max Bytes: The preferred maximum number of bytes allowed for
        # the serialized messages in a batch. A message larger than the preferred
        # max bytes will result in a batch larger than preferred max bytes.
        PreferredMaxBytes: 512 KB

    Kafka:
        # Brokers: A list of Kafka brokers to which the orderer connects
        # NOTE: Use IP:port notation
        Brokers: 
            - kafka0-bankconsortiumbcnet-com:30300 
            - kafka1-bankconsortiumbcnet-com:30302 
            - kafka2-bankconsortiumbcnet-com:30304 
            - kafka3-bankconsortiumbcnet-com:30306 
    # Organizations is the list of orgs which are defined as participants on
    # the orderer side of the network
    Organizations:

################################################################################
#
#   SECTION: Application
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for application related parameters
#
################################################################################
Application: &ApplicationDefaults

    # Organizations is the list of orgs which are defined as participants on
    # the application side of the network
    Organizations:

################################################################################
#
#   SECTION: Capabilities
#
#   - This section defines the capabilities of fabric network. This is a new
#   concept as of v1.1.0 and should not be utilized in mixed networks with
#   v1.0.x peers and orderers.  Capabilities define features which must be
#   present in a fabric binary for that binary to safely participate in the
#   fabric network.  For instance, if a new MSP type is added, newer binaries
#   might recognize and validate the signatures from this type, while older
#   binaries without this support would be unable to validate those
#   transactions.  This could lead to different versions of the fabric binaries
#   having different world states.  Instead, defining a capability for a channel
#   informs those binaries without this capability that they must cease
#   processing transactions until they have been upgraded.  For v1.0.x if any
#   capabilities are defined (including a map with all capabilities turned off)
#   then the v1.0.x peer will deliberately crash.
#
################################################################################
Capabilities:
    # Channel capabilities apply to both the orderers and the peers and must be
    # supported by both.  Set the value of the capability to true to require it.
    Global: &ChannelCapabilities
        # V1.1 for Global is a catchall flag for behavior which has been
        # determined to be desired for all orderers and peers running v1.0.x,
        # but the modification of which would cause incompatibilities.  Users
        # should leave this flag set to true.
        V1_1: true

    # Orderer capabilities apply only to the orderers, and may be safely
    # manipulated without concern for upgrading peers.  Set the value of the
    # capability to true to require it.
    Orderer: &OrdererCapabilities
        # V1.1 for Order is a catchall flag for behavior which has been
        # determined to be desired for all orderers running v1.0.x, but the
        # modification of which  would cause incompatibilities.  Users should
        # leave this flag set to true.
        V1_1: true

    # Application capabilities apply only to the peer network, and may be safely
    # manipulated without concern for upgrading orderers.  Set the value of the
    # capability to true to require it.
    Application: &ApplicationCapabilities
        # V1.1 for Application is a catchall flag for behavior which has been
        # determined to be desired for all peers running v1.0.x, but the
        # modification of which would cause incompatibilities.  Users should
        # leave this flag set to true.
        V1_1: true
################################################################################
#
#   Profile
#
#   - Different configuration profiles may be encoded here to be specified
#   as parameters to the configtxgen tool
#
################################################################################
Profiles:

    OrgsOrdererGenesis:
        Capabilities:
            <<: *ChannelCapabilities
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *sbi
                    - *hdfc
                    - *icici
                    - *pnb
#neworgconsortium
    chsbihdfcChannel:
        Consortium: SampleConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                    - *sbi
                    - *hdfc
#chsbihdfcconfigtx
            Capabilities:
                <<: *ApplicationCapabilities
    chhdfciciciChannel:
        Consortium: SampleConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                    - *hdfc
                    - *icici
#chhdfciciciconfigtx
            Capabilities:
                <<: *ApplicationCapabilities
    chicicisbiChannel:
        Consortium: SampleConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                    - *icici
                    - *sbi
#chicicisbiconfigtx
            Capabilities:
                <<: *ApplicationCapabilities
    challChannel:
        Consortium: SampleConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                    - *sbi
                    - *pnb
                    - *sbi
#challconfigtx
#newchannelconfigtx
