---
apiVersion: batch/v1
kind: Job
metadata:
  name: jcit-chsbihdfccc-golang-chsbihdfc-peer0-sbi
  namespace: bankconsortiumbcnet
spec:
  backoffLimit: 1
  template:
    metadata:
      name: jcit-chsbihdfccc-golang-chsbihdfc-peer0-sbi
    spec:
      restartPolicy: "Never"
      volumes:
      - name: bankconsortiumbcnetvolume
        persistentVolumeClaim:
          claimName: bankconsortiumbcnet-pvc
      - name: dockersocket
        hostPath:
          path: /var/run/docker.sock
      containers:
      - name: jcit-chsbihdfccc-golang-chsbihdfc-peer0-sbi
        image: hyperledger/fabric-tools:latest
        imagePullPolicy: Always
        command: ["sh", "-c", "cd /opt/gopath/src/github.com/hyperledger/fabric/peer ; peer chaincode install -n ${CHAINCODE_NAME} -v ${CHAINCODE_VERSION} -l ${CC_LANGUAGE} -p ${CC_FOLDER} && touch ./status-files/status_installchaincode-${CHAINCODE_NAME}-${CHAINCODE_VERSION}-${CC_LANGUAGE}-${CHANNEL_NAME}-peer0-sbi_complete"]
        env:
        - name: CHAINCODE_NAME
          value: "chsbihdfccc"
        - name: CHAINCODE_VERSION
          value: "1.0"        
        - name: CC_FOLDER
          value: "github.com/chaincode/chaincode_example02/go/"
        - name: CC_LANGUAGE
          value: "golang"  
        - name: CHANNEL_NAME
          value: "chsbihdfc"                              
        - name: CORE_PEER_ADDRESSAUTODETECT
          value: "true"
        - name: CORE_PEER_NETWORKID
          value: "bankconsortiumbcnet"
        - name: CORE_PEER_ADDRESS
          value: "peer0-sbi-bankconsortiumbcnet-com:30011"         
        - name: CORE_PEER_LOCALMSPID
          value: "sbiMSP"
        - name: CORE_PEER_MSPID
          value: "sbiMSP"
        - name: CORE_PEER_MSPCONFIGPATH
          value: "/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/sbi-bankconsortiumbcnet-com/users/Admin@sbi-bankconsortiumbcnet-com/msp"
        - name: CORE_LOGGING_LEVEL
          value: "debug"
        - name: FABRIC_CFG_PATH
          value: "/etc/hyperledger/fabric"
        - name: CORE_PEER_TLS_ENABLED
          value: "true"
        - name: CORE_PEER_TLS_CERT_FILE
          value: "/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/sbi-bankconsortiumbcnet-com/peers/peer0-sbi-bankconsortiumbcnet-com/tls/server.crt"
        - name: CORE_PEER_TLS_KEY_FILE
          value: "/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/sbi-bankconsortiumbcnet-com/peers/peer0-sbi-bankconsortiumbcnet-com/tls/server.key"
        - name: CORE_PEER_TLS_ROOTCERT_FILE
          value: "/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/sbi-bankconsortiumbcnet-com/peers/peer0-sbi-bankconsortiumbcnet-com/tls/ca.crt"
        - name: GODEBUG
          value: "netdns=go"
        - name: GOPATH
          value: "/opt/gopath" 
        volumeMounts:
        - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
          name: bankconsortiumbcnetvolume
          subPath: crypto-config/
        - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts/
          name: bankconsortiumbcnetvolume
          subPath: channel-artifacts/
        - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/status-files/
          name: bankconsortiumbcnetvolume
          subPath: status-files/
        - mountPath: /opt/gopath/src/github.com/chaincode/
          name: bankconsortiumbcnetvolume
          subPath: chaincode/ 
