apiVersion: v1
kind: ConfigMap
metadata:
 name: peerbaseconfigmap
 namespace: bankconsortiumbcnet
data:    
  CORE_LOGGING_LEVEL: "INFO"
  CORE_PEER_TLS_ENABLED: "true"
  CORE_PEER_TLS_CERT_FILE: "/etc/hyperledger/fabric/tls/server.crt"
  CORE_PEER_TLS_KEY_FILE: "/etc/hyperledger/fabric/tls/server.key"
  CORE_PEER_TLS_ROOTCERT_FILE: "/etc/hyperledger/fabric/tls/ca.crt"
  CORE_PEER_GOSSIP_USELEADERELECTION: "true"
  CORE_PEER_GOSSIP_ORGLEADER: "false"
  CORE_PEER_PROFILE_ENABLED: "true"
  CORE_PEER_ADDRESSAUTODETECT: "true"
  CORE_PEER_NETWORKID: "bankconsortiumbcnet"
  CORE_PEER_GOSSIP_SKIPHANDSHAKE: "true"
  CORE_PEER_COMMITTER_ENABLED: "true"
  CORE_VM_ENDPOINT: "unix:///host/var/run/docker.sock"
  CORE_LOGGING_LEVEL: "debug"
  CORE_LOGGING_PEER: "debug"
  CORE_LOGGING_CAUTHDSL: "debug"
  CORE_LOGGING_GOSSIP: "debug"
  CORE_LOGGING_LEDGER: "debug"
  CORE_LOGGING_MSP: "info"
  CORE_LOGGING_POLICIES: "debug"
  CORE_LOGGING_GRPC: "debug"
  FABRIC_CFG_PATH: "/etc/hyperledger/fabric/"
  GODEBUG: "netdns=go"
  CORE_VM_DOCKER_ATTACHSTDOUT: "true" 
