---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ca-pnb-bankconsortiumbcnet-com
  namespace: bankconsortiumbcnet
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: ca-pnb-bankconsortiumbcnet-com
        app: hyperledger
        role: ca
        org: pnb
    spec:
      volumes:
      - name: bankconsortiumbcnetvolume
        persistentVolumeClaim:
          claimName: bankconsortiumbcnet-pvc

      containers:
      - name: ca-pnb-bankconsortiumbcnet
        image: hyperledger/fabric-ca:latest
        command: ["sh", "-c", "export FABRIC_CA_SERVER_TLS_KEYFILE=$(ls /etc/hyperledger/fabric-ca-server-config/*_sk) && while [ ! -f /etc/hyperledger/status-files/status_gc-pnb_complete ]; do echo Waiting for cryptos to be generated; sleep 1; done; fabric-ca-server start  --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca-pnb-bankconsortiumbcnet-com-cert.pem --ca.keyfile ${FABRIC_CA_SERVER_TLS_KEYFILE}  -b admin:adminpw -d"]
        env:
        - name: FABRIC_CA_SERVER_CA_NAME
          value: ca-pnb-bankconsortiumbcnet           
        - name: FABRIC_CA_SERVER_TLS_CERTFILE
          value: /etc/hyperledger/fabric-ca-server-config/ca-pnb-bankconsortiumbcnet-com-cert.pem
        - name: FABRIC_CA_SERVER_DEBUG
          value: "true"
        - name: FABRIC_CA_SERVER_TLS_ENABLED
          value: "true"          
        - name: GODEBUG
          value: "netdns=go"
        ports:
         - containerPort: 7054           
        volumeMounts:
         - mountPath: /etc/hyperledger/fabric-ca-server-config
           name: bankconsortiumbcnetvolume
           subPath: crypto-config/peerOrganizations/pnb-bankconsortiumbcnet-com/ca/
         - mountPath: /etc/hyperledger/status-files/
           name: bankconsortiumbcnetvolume
           subPath: status-files/             
     
        
