---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: peer0-pnb-bankconsortiumbcnet-com
  namespace: bankconsortiumbcnet
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: peer0-pnb-bankconsortiumbcnet
        app: hyperledger
        role: peer
        peer-id: "0"
        org: pnb
    spec:
      volumes:
      - name: bankconsortiumbcnetvolume
        persistentVolumeClaim:
          claimName: bankconsortiumbcnet-pvc
      - name: dockersocket
        hostPath:
          path: /var/run/docker.sock

      containers:
      - name: couchdb-peer0-pnb-bankconsortiumbcnet
        image: hyperledger/fabric-couchdb:latest
        ports:
         - containerPort: 5984

      - name: peer0-pnb-bankconsortiumbcnet
        image: hyperledger/fabric-peer:latest
        command: ["sh", "-c", "sleep 1 && while [ ! -f ./status-files/status_gc-pnb_complete ]; do echo Waiting for cryptos of org; sleep 1; done; peer node start"]
        workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        envFrom:
         - configMapRef:
             name: peerbaseconfigmap
        env:
        - name: CORE_LEDGER_STATE_STATEDATABASE
          value: "CouchDB"
        - name: CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS
          value: "localhost:5984"  
        - name: ORDERER_URL
          value: "orderer0-bankconsortiumbcnet-com:30000" 
        - name: CORE_PEER_ID
          value: "peer0-pnb-bankconsortiumbcnet-com"
        - name: CORE_PEER_ADDRESS
          value: "peer0-pnb-bankconsortiumbcnet-com:30023"
        - name: CORE_PEER_LISTENADDRESS
          value: "0.0.0.0:30023"
        - name: CORE_PEER_EVENTS_ADDRESS
          value: "0.0.0.0:30024"
        - name: CORE_PEER_GOSSIP_BOOTSTRAP
          value: "peer0-pnb-bankconsortiumbcnet-com:30023"
        - name: CORE_PEER_LOCALMSPID
          value: "pnbMSP"
        - name: CORE_PEER_MSPID
          value: "pnbMSP"          
        - name: CORE_PEER_MSPCONFIGPATH
          value: "/etc/hyperledger/fabric/msp"
        ports:
         - containerPort: 30023
           name: grpc          
         - containerPort: 30024
           name: events                    
        volumeMounts:
        - mountPath: /etc/hyperledger/fabric/msp 
          name: bankconsortiumbcnetvolume
          subPath: crypto-config/peerOrganizations/pnb-bankconsortiumbcnet-com/peers/peer0-pnb-bankconsortiumbcnet-com/msp
        - mountPath: /etc/hyperledger/fabric/tls 
          name: bankconsortiumbcnetvolume
          subPath: crypto-config/peerOrganizations/pnb-bankconsortiumbcnet-com/peers/peer0-pnb-bankconsortiumbcnet-com/tls
        - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts 
          name: bankconsortiumbcnetvolume
          subPath: channel-artifacts
        - mountPath: /host/var/run/docker.sock
          name: dockersocket
        - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/status-files/
          name: bankconsortiumbcnetvolume
          subPath: status-files/                  

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: peer1-pnb-bankconsortiumbcnet-com
  namespace: bankconsortiumbcnet
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: peer1-pnb-bankconsortiumbcnet
        app: hyperledger
        role: peer
        peer-id: "1"
        org: pnb
    spec:
      volumes:
      - name: bankconsortiumbcnetvolume
        persistentVolumeClaim:
          claimName: bankconsortiumbcnet-pvc
      - name: dockersocket
        hostPath:
          path: /var/run/docker.sock

      containers:
      - name: couchdb-peer1-pnb-bankconsortiumbcnet
        image: hyperledger/fabric-couchdb:latest
        ports:
         - containerPort: 5984

      - name: peer1-pnb-bankconsortiumbcnet
        image: hyperledger/fabric-peer:latest
        command: ["sh", "-c", "sleep 1 && while [ ! -f ./status-files/status_gc-pnb_complete ]; do echo Waiting for cryptos of org; sleep 1; done; peer node start"]
        workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        envFrom:
         - configMapRef:
             name: peerbaseconfigmap
        env:
        - name: CORE_LEDGER_STATE_STATEDATABASE
          value: "CouchDB"
        - name: CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS
          value: "localhost:5984"
        - name: ORDERER_URL
          value: "orderer1-bankconsortiumbcnet-com:30001"        
        - name: CORE_PEER_ID
          value: "peer1-pnb-bankconsortiumbcnet-com"
        - name: CORE_PEER_ADDRESS
          value: "peer1-pnb-bankconsortiumbcnet-com:30025"
        - name: CORE_PEER_LISTENADDRESS
          value: "0.0.0.0:30025"
        - name: CORE_PEER_EVENTS_ADDRESS
          value: "0.0.0.0:30026"
        - name: CORE_PEER_GOSSIP_BOOTSTRAP
          value: "peer1-pnb-bankconsortiumbcnet-com:30025"
        - name: CORE_PEER_LOCALMSPID
          value: "pnbMSP"
        - name: CORE_PEER_MSPID
          value: "pnbMSP"          
        - name: CORE_PEER_MSPCONFIGPATH
          value: "/etc/hyperledger/fabric/msp"
        ports:
         - containerPort: 30025
           name: grpc          
         - containerPort: 30026
           name: events                   
        volumeMounts:
        - mountPath: /etc/hyperledger/fabric/msp 
          name: bankconsortiumbcnetvolume
          subPath: crypto-config/peerOrganizations/pnb-bankconsortiumbcnet-com/peers/peer1-pnb-bankconsortiumbcnet-com/msp
        - mountPath: /etc/hyperledger/fabric/tls 
          name: bankconsortiumbcnetvolume
          subPath: crypto-config/peerOrganizations/pnb-bankconsortiumbcnet-com/peers/peer1-pnb-bankconsortiumbcnet-com/tls
        - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts 
          name: bankconsortiumbcnetvolume
          subPath: channel-artifacts
        - mountPath: /host/var/run/docker.sock
          name: dockersocket
        - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/status-files/
          name: bankconsortiumbcnetvolume
          subPath: status-files/                  

