---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: peer0-sbi-bankconsortiumbcnet-com
  namespace: bankconsortiumbcnet
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: peer0-sbi-bankconsortiumbcnet
        app: hyperledger
        role: peer
        peer-id: "0"
        org: sbi
    spec:
      volumes:
      - name: bankconsortiumbcnetvolume
        persistentVolumeClaim:
          claimName: bankconsortiumbcnet-pvc
      - name: dockersocket
        hostPath:
          path: /var/run/docker.sock

      containers:
      - name: couchdb-peer0-sbi-bankconsortiumbcnet
        image: hyperledger/fabric-couchdb:latest
        ports:
         - containerPort: 5984

      - name: peer0-sbi-bankconsortiumbcnet
        image: hyperledger/fabric-peer:latest
        command: ["sh", "-c", "sleep 1 && while [ ! -f ./status-files/status_configtxgen_complete ]; do echo Waiting for configtxgen; sleep 1; done; peer node start"]
        workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        envFrom:
         - configMapRef:
             name: peerbaseconfigmap
        env:
        - name: CORE_LEDGER_STATE_STATEDATABASE
          value: "CouchDB"
        - name: CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS
          value: "localhost:5984"
        - name: ORDERER_URL
          value: "orderer0-bankconsortiumbcnet-com:30000"                   
        - name: CORE_PEER_ID
          value: "peer0-sbi-bankconsortiumbcnet-com"
        - name: CORE_PEER_ADDRESS
          value: "peer0-sbi-bankconsortiumbcnet-com:30011"
        - name: CORE_PEER_LISTENADDRESS
          value: "0.0.0.0:30011"
        - name: CORE_PEER_EVENTS_ADDRESS
          value: "0.0.0.0:30012"
        - name: CORE_PEER_GOSSIP_BOOTSTRAP
          value: "peer0-sbi-bankconsortiumbcnet-com:30011"
        - name: CORE_PEER_LOCALMSPID
          value: "sbiMSP"
        - name: CORE_PEER_MSPID
          value: "sbiMSP"          
        - name: CORE_PEER_MSPCONFIGPATH
          value: "/etc/hyperledger/fabric/msp"
        ports:
         - containerPort: 30011
           name: grpc          
         - containerPort: 30012
           name: events 
        volumeMounts:
        - mountPath: "/etc/hyperledger/fabric/msp" 
          name: bankconsortiumbcnetvolume
          subPath: crypto-config/peerOrganizations/sbi-bankconsortiumbcnet-com/peers/peer0-sbi-bankconsortiumbcnet-com/msp
        - mountPath: /etc/hyperledger/fabric/tls 
          name: bankconsortiumbcnetvolume
          subPath: crypto-config/peerOrganizations/sbi-bankconsortiumbcnet-com/peers/peer0-sbi-bankconsortiumbcnet-com/tls
        - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts 
          name: bankconsortiumbcnetvolume
          subPath: channel-artifacts
        - mountPath: /host/var/run/docker.sock
          name: dockersocket
        - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/status-files/
          name: bankconsortiumbcnetvolume
          subPath: status-files/            
          

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: peer0-hdfc-bankconsortiumbcnet-com
  namespace: bankconsortiumbcnet
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: peer0-hdfc-bankconsortiumbcnet
        app: hyperledger
        role: peer
        peer-id: "0"
        org: hdfc
    spec:
      volumes:
      - name: bankconsortiumbcnetvolume
        persistentVolumeClaim:
          claimName: bankconsortiumbcnet-pvc
      - name: dockersocket
        hostPath:
          path: /var/run/docker.sock

      containers:
      - name: couchdb-peer0-hdfc-bankconsortiumbcnet
        image: hyperledger/fabric-couchdb:latest
        ports:
         - containerPort: 5984

      - name: peer0-hdfc-bankconsortiumbcnet
        image: hyperledger/fabric-peer:latest
        command: ["sh", "-c", "sleep 1 && while [ ! -f ./status-files/status_configtxgen_complete ]; do echo Waiting for configtxgen; sleep 1; done; peer node start"]
        workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        envFrom:
         - configMapRef:
             name: peerbaseconfigmap
        env:
        - name: CORE_LEDGER_STATE_STATEDATABASE
          value: "CouchDB"
        - name: CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS
          value: "localhost:5984"
        - name: ORDERER_URL
          value: "orderer1-bankconsortiumbcnet-com:30001"                   
        - name: CORE_PEER_ID
          value: "peer0-hdfc-bankconsortiumbcnet-com"
        - name: CORE_PEER_ADDRESS
          value: "peer0-hdfc-bankconsortiumbcnet-com:30013"
        - name: CORE_PEER_LISTENADDRESS
          value: "0.0.0.0:30013"
        - name: CORE_PEER_EVENTS_ADDRESS
          value: "0.0.0.0:30014"
        - name: CORE_PEER_GOSSIP_BOOTSTRAP
          value: "peer0-hdfc-bankconsortiumbcnet-com:30013"
        - name: CORE_PEER_LOCALMSPID
          value: "hdfcMSP"
        - name: CORE_PEER_MSPID
          value: "hdfcMSP"          
        - name: CORE_PEER_MSPCONFIGPATH
          value: "/etc/hyperledger/fabric/msp"
        ports:
         - containerPort: 30013
           name: grpc          
         - containerPort: 30014
           name: events 
        volumeMounts:
        - mountPath: "/etc/hyperledger/fabric/msp" 
          name: bankconsortiumbcnetvolume
          subPath: crypto-config/peerOrganizations/hdfc-bankconsortiumbcnet-com/peers/peer0-hdfc-bankconsortiumbcnet-com/msp
        - mountPath: /etc/hyperledger/fabric/tls 
          name: bankconsortiumbcnetvolume
          subPath: crypto-config/peerOrganizations/hdfc-bankconsortiumbcnet-com/peers/peer0-hdfc-bankconsortiumbcnet-com/tls
        - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts 
          name: bankconsortiumbcnetvolume
          subPath: channel-artifacts
        - mountPath: /host/var/run/docker.sock
          name: dockersocket
        - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/status-files/
          name: bankconsortiumbcnetvolume
          subPath: status-files/            
          

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: peer1-hdfc-bankconsortiumbcnet-com
  namespace: bankconsortiumbcnet
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: peer1-hdfc-bankconsortiumbcnet
        app: hyperledger
        role: peer
        peer-id: "1"
        org: hdfc
    spec:
      volumes:
      - name: bankconsortiumbcnetvolume
        persistentVolumeClaim:
          claimName: bankconsortiumbcnet-pvc
      - name: dockersocket
        hostPath:
          path: /var/run/docker.sock

      containers:
      - name: couchdb-peer1-hdfc-bankconsortiumbcnet
        image: hyperledger/fabric-couchdb:latest
        ports:
         - containerPort: 5984

      - name: peer1-hdfc-bankconsortiumbcnet
        image: hyperledger/fabric-peer:latest
        command: ["sh", "-c", "sleep 1 && while [ ! -f ./status-files/status_configtxgen_complete ]; do echo Waiting for configtxgen; sleep 1; done; peer node start"]
        workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        envFrom:
         - configMapRef:
             name: peerbaseconfigmap
        env:
        - name: CORE_LEDGER_STATE_STATEDATABASE
          value: "CouchDB"
        - name: CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS
          value: "localhost:5984"
        - name: ORDERER_URL
          value: "orderer0-bankconsortiumbcnet-com:30000"           
        - name: CORE_PEER_ID
          value: "peer1-hdfc-bankconsortiumbcnet-com"
        - name: CORE_PEER_ADDRESS
          value: "peer1-hdfc-bankconsortiumbcnet-com:30015"
        - name: CORE_PEER_LISTENADDRESS
          value: "0.0.0.0:30015"
        - name: CORE_PEER_EVENTS_ADDRESS
          value: "0.0.0.0:30016"
        - name: CORE_PEER_GOSSIP_BOOTSTRAP
          value: "peer1-hdfc-bankconsortiumbcnet-com:30015"
        - name: CORE_PEER_LOCALMSPID
          value: "hdfcMSP"
        - name: CORE_PEER_MSPID
          value: "hdfcMSP"          
        - name: CORE_PEER_MSPCONFIGPATH
          value: "/etc/hyperledger/fabric/msp"
        ports:
         - containerPort: 30015
           name: grpc          
         - containerPort: 30016
           name: events        
        volumeMounts:
        - mountPath: /etc/hyperledger/fabric/msp 
          name: bankconsortiumbcnetvolume
          subPath: crypto-config/peerOrganizations/hdfc-bankconsortiumbcnet-com/peers/peer1-hdfc-bankconsortiumbcnet-com/msp
        - mountPath: /etc/hyperledger/fabric/tls 
          name: bankconsortiumbcnetvolume
          subPath: crypto-config/peerOrganizations/hdfc-bankconsortiumbcnet-com/peers/peer1-hdfc-bankconsortiumbcnet-com/tls
        - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts 
          name: bankconsortiumbcnetvolume
          subPath: channel-artifacts
        - mountPath: /host/var/run/docker.sock
          name: dockersocket
        - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/status-files/
          name: bankconsortiumbcnetvolume
          subPath: status-files/            
          

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: peer0-icici-bankconsortiumbcnet-com
  namespace: bankconsortiumbcnet
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: peer0-icici-bankconsortiumbcnet
        app: hyperledger
        role: peer
        peer-id: "0"
        org: icici
    spec:
      volumes:
      - name: bankconsortiumbcnetvolume
        persistentVolumeClaim:
          claimName: bankconsortiumbcnet-pvc
      - name: dockersocket
        hostPath:
          path: /var/run/docker.sock

      containers:
      - name: couchdb-peer0-icici-bankconsortiumbcnet
        image: hyperledger/fabric-couchdb:latest
        ports:
         - containerPort: 5984

      - name: peer0-icici-bankconsortiumbcnet
        image: hyperledger/fabric-peer:latest
        command: ["sh", "-c", "sleep 1 && while [ ! -f ./status-files/status_configtxgen_complete ]; do echo Waiting for configtxgen; sleep 1; done; peer node start"]
        workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        envFrom:
         - configMapRef:
             name: peerbaseconfigmap
        env:
        - name: CORE_LEDGER_STATE_STATEDATABASE
          value: "CouchDB"
        - name: CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS
          value: "localhost:5984"
        - name: ORDERER_URL
          value: "orderer1-bankconsortiumbcnet-com:30001"                   
        - name: CORE_PEER_ID
          value: "peer0-icici-bankconsortiumbcnet-com"
        - name: CORE_PEER_ADDRESS
          value: "peer0-icici-bankconsortiumbcnet-com:30017"
        - name: CORE_PEER_LISTENADDRESS
          value: "0.0.0.0:30017"
        - name: CORE_PEER_EVENTS_ADDRESS
          value: "0.0.0.0:30018"
        - name: CORE_PEER_GOSSIP_BOOTSTRAP
          value: "peer0-icici-bankconsortiumbcnet-com:30017"
        - name: CORE_PEER_LOCALMSPID
          value: "iciciMSP"
        - name: CORE_PEER_MSPID
          value: "iciciMSP"          
        - name: CORE_PEER_MSPCONFIGPATH
          value: "/etc/hyperledger/fabric/msp"
        ports:
         - containerPort: 30017
           name: grpc          
         - containerPort: 30018
           name: events 
        volumeMounts:
        - mountPath: "/etc/hyperledger/fabric/msp" 
          name: bankconsortiumbcnetvolume
          subPath: crypto-config/peerOrganizations/icici-bankconsortiumbcnet-com/peers/peer0-icici-bankconsortiumbcnet-com/msp
        - mountPath: /etc/hyperledger/fabric/tls 
          name: bankconsortiumbcnetvolume
          subPath: crypto-config/peerOrganizations/icici-bankconsortiumbcnet-com/peers/peer0-icici-bankconsortiumbcnet-com/tls
        - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts 
          name: bankconsortiumbcnetvolume
          subPath: channel-artifacts
        - mountPath: /host/var/run/docker.sock
          name: dockersocket
        - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/status-files/
          name: bankconsortiumbcnetvolume
          subPath: status-files/            
          

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: peer1-icici-bankconsortiumbcnet-com
  namespace: bankconsortiumbcnet
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: peer1-icici-bankconsortiumbcnet
        app: hyperledger
        role: peer
        peer-id: "1"
        org: icici
    spec:
      volumes:
      - name: bankconsortiumbcnetvolume
        persistentVolumeClaim:
          claimName: bankconsortiumbcnet-pvc
      - name: dockersocket
        hostPath:
          path: /var/run/docker.sock

      containers:
      - name: couchdb-peer1-icici-bankconsortiumbcnet
        image: hyperledger/fabric-couchdb:latest
        ports:
         - containerPort: 5984

      - name: peer1-icici-bankconsortiumbcnet
        image: hyperledger/fabric-peer:latest
        command: ["sh", "-c", "sleep 1 && while [ ! -f ./status-files/status_configtxgen_complete ]; do echo Waiting for configtxgen; sleep 1; done; peer node start"]
        workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        envFrom:
         - configMapRef:
             name: peerbaseconfigmap
        env:
        - name: CORE_LEDGER_STATE_STATEDATABASE
          value: "CouchDB"
        - name: CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS
          value: "localhost:5984"
        - name: ORDERER_URL
          value: "orderer0-bankconsortiumbcnet-com:30000"           
        - name: CORE_PEER_ID
          value: "peer1-icici-bankconsortiumbcnet-com"
        - name: CORE_PEER_ADDRESS
          value: "peer1-icici-bankconsortiumbcnet-com:30019"
        - name: CORE_PEER_LISTENADDRESS
          value: "0.0.0.0:30019"
        - name: CORE_PEER_EVENTS_ADDRESS
          value: "0.0.0.0:30020"
        - name: CORE_PEER_GOSSIP_BOOTSTRAP
          value: "peer1-icici-bankconsortiumbcnet-com:30019"
        - name: CORE_PEER_LOCALMSPID
          value: "iciciMSP"
        - name: CORE_PEER_MSPID
          value: "iciciMSP"          
        - name: CORE_PEER_MSPCONFIGPATH
          value: "/etc/hyperledger/fabric/msp"
        ports:
         - containerPort: 30019
           name: grpc          
         - containerPort: 30020
           name: events        
        volumeMounts:
        - mountPath: /etc/hyperledger/fabric/msp 
          name: bankconsortiumbcnetvolume
          subPath: crypto-config/peerOrganizations/icici-bankconsortiumbcnet-com/peers/peer1-icici-bankconsortiumbcnet-com/msp
        - mountPath: /etc/hyperledger/fabric/tls 
          name: bankconsortiumbcnetvolume
          subPath: crypto-config/peerOrganizations/icici-bankconsortiumbcnet-com/peers/peer1-icici-bankconsortiumbcnet-com/tls
        - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts 
          name: bankconsortiumbcnetvolume
          subPath: channel-artifacts
        - mountPath: /host/var/run/docker.sock
          name: dockersocket
        - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/status-files/
          name: bankconsortiumbcnetvolume
          subPath: status-files/            
          

