---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka0-bankconsortiumbcnet-com
  namespace: bankconsortiumbcnet
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: kafka0-bankconsortiumbcnet
        app: hyperledger
        role: kafka0
        org: bankconsortiumbcnet 
    spec:
      containers:
      - name: kafka0-bankconsortiumbcnet
        image: hyperledger/fabric-kafka:latest
        envFrom:
         - configMapRef:
             name: kafkaconfigmap
        env:
        - name: KAFKA_BROKER_ID
          value: "0"
        - name: KAFKA_ADVERTISED_PORT
          value: "30300"
        - name: KAFKA_PORT
          value: "30300"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "kafka0-bankconsortiumbcnet-com"                                      
        ports:
         - containerPort: 30300
           name: kafka-port
         - containerPort: 30301   

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka1-bankconsortiumbcnet-com
  namespace: bankconsortiumbcnet
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: kafka1-bankconsortiumbcnet
        app: hyperledger
        role: kafka1
        org: bankconsortiumbcnet 
    spec:
      containers:
      - name: kafka1-bankconsortiumbcnet
        image: hyperledger/fabric-kafka:latest
        envFrom:
         - configMapRef:
             name: kafkaconfigmap
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ADVERTISED_PORT
          value: "30302"
        - name: KAFKA_PORT
          value: "30302"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "kafka1-bankconsortiumbcnet-com"                                      
        ports:
         - containerPort: 30302
           name: kafka-port
         - containerPort: 30303   

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka2-bankconsortiumbcnet-com
  namespace: bankconsortiumbcnet
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: kafka2-bankconsortiumbcnet
        app: hyperledger
        role: kafka2
        org: bankconsortiumbcnet 
    spec:
      containers:
      - name: kafka2-bankconsortiumbcnet
        image: hyperledger/fabric-kafka:latest
        envFrom:
         - configMapRef:
             name: kafkaconfigmap
        env:
        - name: KAFKA_BROKER_ID
          value: "2"
        - name: KAFKA_ADVERTISED_PORT
          value: "30304"
        - name: KAFKA_PORT
          value: "30304"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "kafka2-bankconsortiumbcnet-com"                                      
        ports:
         - containerPort: 30304
           name: kafka-port
         - containerPort: 30305   

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka3-bankconsortiumbcnet-com
  namespace: bankconsortiumbcnet
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: kafka3-bankconsortiumbcnet
        app: hyperledger
        role: kafka3
        org: bankconsortiumbcnet 
    spec:
      containers:
      - name: kafka3-bankconsortiumbcnet
        image: hyperledger/fabric-kafka:latest
        envFrom:
         - configMapRef:
             name: kafkaconfigmap
        env:
        - name: KAFKA_BROKER_ID
          value: "3"
        - name: KAFKA_ADVERTISED_PORT
          value: "30306"
        - name: KAFKA_PORT
          value: "30306"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "kafka3-bankconsortiumbcnet-com"                                      
        ports:
         - containerPort: 30306
           name: kafka-port
         - containerPort: 30307   

