---
apiVersion: v1
kind: Service
metadata:
  name: peer1-sbi-bankconsortiumbcnet-com
  namespace: bankconsortiumbcnet
  labels:
    run: peer1-sbi-bankconsortiumbcnet-com
spec:
  type: NodePort
  selector:
    name: peer1-sbi-bankconsortiumbcnet
  ports:
  - protocol: TCP
    nodePort: 30021
    targetPort: 30021
    port: 30021
    name: grpc
  - protocol: TCP
    nodePort: 30022
    targetPort: 30022
    port: 30022
    name: events
    
    
