---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: bankconsortiumbcnet-pv
  namespace: bankconsortiumbcnet
  labels:
    type: local
    name: bankconsortiumbcnetvolume
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp/nfsshare/"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bankconsortiumbcnet-pvc
  namespace: bankconsortiumbcnet
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: bankconsortiumbcnetvolume
      
      
