---
apiVersion: batch/v1
kind: Job
metadata:
  name: jaotc-sbi-chall-part1
  namespace: bankconsortiumbcnet
spec:
  backoffLimit: 1
  template:
    metadata:
       labels:
           name: jaotc-sbi-chall-part1
    spec:
      restartPolicy: "Never"
      volumes:
      - name: bankconsortiumbcnetvolume
        persistentVolumeClaim:
          claimName: bankconsortiumbcnet-pvc
      - name: dockersocket
        hostPath:
          path: /var/run/docker.sock
      containers:
      - name: jaotc-sbi-chall-part1
        image: piyushkumar96/fabric-tools
        imagePullPolicy: Always
        command: ["/bin/bash", "-c", "cd  /opt/gopath/src/github.com/hyperledger/fabric/peer/status-files/ ; ./addorgtochannelp1.sh chall sbi 0 30000"]
        workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer/
        env:
        - name: CHANNEL_NAME
          value: "chall"
        - name: ORDERER_URL
          value: "orderer0-bankconsortiumbcnet-com:30000"
        - name: CORE_PEER_ADDRESSAUTODETECT
          value: "false"
        - name: CORE_PEER_NETWORKID
          value: "bankconsortiumbcnet"
        - name: CORE_PEER_ADDRESS
          value: "peer0-sbi-bankconsortiumbcnet-com:30011"         
        - name: CORE_PEER_LOCALMSPID
          value: "sbiMSP"
        - name: CORE_PEER_MSPID
          value: "sbiMSP"
        - name: CORE_PEER_MSPCONFIGPATH
          value: "/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/sbi-bankconsortiumbcnet-com/users/Admin@sbi-bankconsortiumbcnet-com/msp"
        - name: CORE_LOGGING_LEVEL
          value: "debug"
        - name: FABRIC_CFG_PATH
          value: "/etc/hyperledger/fabric"
        - name: CORE_PEER_TLS_ENABLED
          value: "true"
        - name: CORE_PEER_TLS_CERT_FILE
          value: "/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/sbi-bankconsortiumbcnet-com/peers/peer0-sbi-bankconsortiumbcnet-com/tls/server.crt"
        - name: CORE_PEER_TLS_KEY_FILE
          value: "/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/sbi-bankconsortiumbcnet-com/peers/peer0-sbi-bankconsortiumbcnet-com/tls/server.key"
        - name: CORE_PEER_TLS_ROOTCERT_FILE
          value: "/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/sbi-bankconsortiumbcnet-com/peers/peer0-sbi-bankconsortiumbcnet-com/tls/ca.crt"
        - name: GODEBUG
          value: "netdns=go"
        volumeMounts:
        - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
          name: bankconsortiumbcnetvolume
          subPath: crypto-config/
        - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts/
          name: bankconsortiumbcnetvolume
          subPath: channel-artifacts/
        - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/status-files/
          name: bankconsortiumbcnetvolume
          subPath: status-files/  
