---
apiVersion: batch/v1
kind: Job
metadata:
  name: jcc-chall
  namespace: bankconsortiumbcnet
spec:
  backoffLimit: 1
  template:
    metadata:
      name: createchannel-chall
    spec:
      restartPolicy: "Never"
      volumes:
      - name: bankconsortiumbcnetvolume
        persistentVolumeClaim:
          claimName: bankconsortiumbcnet-pvc
      containers:
      - name: createchanneltx-chall
        image: piyushkumar96/fabric-tools
        imagePullPolicy: Always
        command: ["sh", "-c", "while [ ! -f /bankconsortiumbcnet/artifact-Files/configtx.yaml ]; do echo Waiting for configFiles; sleep 1; done; cp -f /bankconsortiumbcnet/artifact-Files/configtx.yaml /bankconsortiumbcnet/; cd /bankconsortiumbcnet && pwd && ls && export FABRIC_CFG_PATH=$PWD && configtxgen -profile challChannel -outputCreateChannelTx ./channel-artifacts/${CHANNEL_NAME}.tx -channelID ${CHANNEL_NAME} && touch /bankconsortiumbcnet/status-files/status_challtx_complete "]
        env:
        - name: CHANNEL_NAME
          value: "chall"
        - name: GODEBUG
          value: "netdns=go"
        - name: FABRIC_CFG_PATH
          value: "/etc/hyperledger/fabric"
        volumeMounts:
        - mountPath: /bankconsortiumbcnet
          name: bankconsortiumbcnetvolume

      - name: createchannel-chall
        image: hyperledger/fabric-peer:latest
        imagePullPolicy: Always
        command: ["sh", "-c", "cd /opt/gopath/src/github.com/hyperledger/fabric/peer/ && while [ ! -f ./status-files/status_challtx_complete ]; do echo Waiting for challtx; sleep 2; done; peer channel create -o ${ORDERER_URL} -c ${CHANNEL_NAME} -f ./channel-artifacts/${CHANNEL_NAME}.tx --outputBlock ./channel-artifacts/${CHANNEL_NAME}.block --tls --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/bankconsortiumbcnet-com/orderers/orderer0-bankconsortiumbcnet-com/msp/tlscacerts/tlsca-bankconsortiumbcnet-com-cert.pem && rm ./status-files/status_challtx_complete && touch ./status-files/status_channelcreatechall_complete"]
        env:
        - name: CHANNEL_NAME
          value: "chall"
        - name: ORDERER_URL
          value: "orderer0-bankconsortiumbcnet-com:30000"
        - name: CORE_PEER_ADDRESSAUTODETECT
          value: "false"
        - name: CORE_PEER_NETWORKID
          value: "bankconsortiumbcnet"
        - name: CORE_PEER_LOCALMSPID
          value: "sbiMSP"
        - name: CORE_PEER_MSPCONFIGPATH
          value: "/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/sbi-bankconsortiumbcnet-com/users/Admin@sbi-bankconsortiumbcnet-com/msp"
        - name: CORE_LOGGING_LEVEL
          value: "debug"
        - name: FABRIC_CFG_PATH
          value: "/etc/hyperledger/fabric"
        - name: CORE_PEER_TLS_ENABLED
          value: "true"
        - name: CORE_PEER_TLS_CERT_FILE
          value: "/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/sbi-bankconsortiumbcnet-com/peers/peer0-sbi-bankconsortiumbcnet-com/tls/server.crt"
        - name: CORE_PEER_TLS_KEY_FILE
          value: "/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/sbi-bankconsortiumbcnet-com/peers/peer0-sbi-bankconsortiumbcnet-com/tls/server.key"
        - name: CORE_PEER_TLS_ROOTCERT_FILE
          value: "/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/sbi-bankconsortiumbcnet-com/peers/peer0-sbi-bankconsortiumbcnet-com/tls/ca.crt"
        - name: GODEBUG
          value: "netdns=go"
        volumeMounts:
        - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
          name: bankconsortiumbcnetvolume
          subPath: crypto-config/
        - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts/
          name: bankconsortiumbcnetvolume
          subPath: channel-artifacts/
        - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/status-files/
          name: bankconsortiumbcnetvolume
          subPath: status-files/     
